export const url = "http://192.168.3.170:5000/api_booking";
export const apiKey = "oleg";
export const defaultData = [
  {
    day: "0000-00-00",
    event_day: [],
  },
  {
    day: "0000-00-00",
    event_day: [],
  },
  {
    day: "0000-00-00",
    event_day: [],
  },
  {
    day: "0000-00-00",
    event_day: [],
  },
  {
    day: "0000-00-00",
    event_day: [],
  },
  {
    day: "0000-00-00",
    event_day: [],
  },
  {
    day: "0000-00-00",
    event_day: [],
  },
];

export const jsonchick = [
  {
    day: "2022-10-10",
    event_day: [
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-11",
        day_start: "2022-10-10",
        id_event_day: 63,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-10",
        day_start: "2022-10-10",
        id_event_day: 192,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
  {
    day: "2022-10-11",
    event_day: [
      {
        correct_time_end: "03:30:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-11",
        day_start: "2022-10-10",
        id_event_day: 63,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-12",
        day_start: "2022-10-11",
        id_event_day: 64,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-11",
        day_start: "2022-10-11",
        id_event_day: 193,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
  {
    day: "2022-10-12",
    event_day: [
      {
        correct_time_end: "03:30:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-12",
        day_start: "2022-10-11",
        id_event_day: 64,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-13",
        day_start: "2022-10-12",
        id_event_day: 65,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-12",
        day_start: "2022-10-12",
        id_event_day: 194,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
  {
    day: "2022-10-13",
    event_day: [
      {
        correct_time_end: "03:30:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-13",
        day_start: "2022-10-12",
        id_event_day: 65,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-14",
        day_start: "2022-10-13",
        id_event_day: 66,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-13",
        day_start: "2022-10-13",
        id_event_day: 195,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
  {
    day: "2022-10-14",
    event_day: [
      {
        correct_time_end: "03:30:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-14",
        day_start: "2022-10-13",
        id_event_day: 66,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-15",
        day_start: "2022-10-14",
        id_event_day: 67,
        setting_and_booking: {
          event_booking: [
            {
              comment: "",
              connect_user: {
                id_client: 1,
                name_client: "Кроссовки Puma",
                phone_num: "+79991585922",
                tg_id: 123,
              },
              id_booking: 1,
              subscription_service: {
                id: 1,
                name_service: "chistka",
              },
              time_end: "15:00:00",
              time_start: "14:00:00",
            },
            {
              comment: "",
              connect_user: {
                id_client: 1,
                name_client: "Кроссовки Puma",
                phone_num: "+79991585922",
                tg_id: 123,
              },
              id_booking: 2,
              subscription_service: {
                id: 1,
                name_service: "chistka",
              },
              time_end: "17:00:00",
              time_start: "16:00:00",
            },
          ],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-14",
        day_start: "2022-10-14",
        id_event_day: 196,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
  {
    day: "2022-10-15",
    event_day: [
      {
        correct_time_end: "03:30:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-15",
        day_start: "2022-10-14",
        id_event_day: 67,
        setting_and_booking: {
          event_booking: [
            {
              comment: "",
              connect_user: {
                id_client: 1,
                name_client: "Кроссовки Puma",
                phone_num: "+79991585922",
                tg_id: 123,
              },
              id_booking: 1,
              subscription_service: {
                id: 1,
                name_service: "chistka",
              },
              time_end: "15:00:00",
              time_start: "14:00:00",
            },
            {
              comment: "",
              connect_user: {
                id_client: 1,
                name_client: "Кроссовки Puma",
                phone_num: "+79991585922",
                tg_id: 123,
              },
              id_booking: 2,
              subscription_service: {
                id: 1,
                name_service: "chistka",
              },
              time_end: "17:00:00",
              time_start: "16:00:00",
            },
          ],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-16",
        day_start: "2022-10-15",
        id_event_day: 68,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-15",
        day_start: "2022-10-15",
        id_event_day: 197,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
  {
    day: "2022-10-16",
    event_day: [
      {
        correct_time_end: "03:30:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-16",
        day_start: "2022-10-15",
        id_event_day: 68,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "13:30:00",
        day_end: "2022-10-17",
        day_start: "2022-10-16",
        id_event_day: 69,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 18,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-11",
            day_end_rapid: "2022-10-22",
            day_start_g: "2022-10-10",
            event_time_end: "03:30:00",
            event_time_start: "13:30:00",
            id_global_event: 27,
            name_event: "LANCH GOOO",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
      {
        correct_time_end: "23:59:00",
        correct_time_start: "00:00:00",
        day_end: "2022-10-16",
        day_start: "2022-10-16",
        id_event_day: 198,
        setting_and_booking: {
          event_booking: [],
          event_setting: {
            all_services: [
              {
                duration: "01:00:00",
                id: 21,
                id_service: 1,
                max_booking: 1337,
                price_service: 133.7,
              },
            ],
            day_end_g: "2022-10-10",
            day_end_rapid: "2022-10-23",
            day_start_g: "2022-10-10",
            event_time_end: "17:30:00",
            event_time_start: "13:30:00",
            id_global_event: 30,
            name_event: "XEER",
            status_repid_day: true,
            weekdays: [],
          },
        },
      },
    ],
  },
];

export const defaultServices = [
  {
    id: 1,
    name_service: "default",
    max_booking: 1337,
    price_service: 133.7,
    duration: "01:00:00",
  },
];
